### ISSUE TITLE
Background color overlapping texts

### ISSUE THREAD

**Issue by silviolobo** [mao-santaella-rs/NightWolfTheme#23] opened 2019-09-27 12:26 UTC
Loving the theme so far. Specially the name :)

**Issue**
When opening the info from some extensions (I tested with both Bracket Pair Colorizer), it seems that elements \<blockquote\> appears with background color messed up.

**Screenshot**
![image](https://user-images.githubusercontent.com/7155019/65768557-a7ef2880-e107-11e9-93f2-589ec401c44b.png)

**Comment by mao-santaella-rs** [comment] 2019-11-08 04:22
Hi Silvio thanks for taking the time to make the issue, and awesome that you like the name :), the issue is fixed in v1.8.2, let me know if you found anything else. thanks

**Closed by mao-santaella-rs** 2019-11-08 04:22 UTC
